language: python
python:
    - 2.7

dist: trusty
sudo: required

before_cache:
  - rm -f $HOME/miniconda/pkgs/*.tar.bz2
  - rm -rf $HOME/miniconda/pkgs/cache

cache:
  apt: true
  directories:
    - $HOME/miniconda

# Install conda packages
install:
  - conda install --yes -c https://conda.binstar.org/faircloth-lab python=$TRAVIS_PYTHON_VERSION numpy=1.7 biopython=1.62 pytest=2.4.2 abyss velvet lastz mafft
  - python setup.py install

addons:
  apt:
    packages:
      - mysql-client-5.6
      - mysql-client-core-5.6
      - mysql-server-5.6
  hosts:
    - localhost

script:
  - make ci-test
