language: python
python:
    - 2.7.10

dist: trusty
sudo: required

before_cache:
  - rm -f $HOME/miniconda/pkgs/*.tar.bz2
  - rm -rf $HOME/miniconda/pkgs/cache

cache:
  apt: true
  directories:
    - $HOME/miniconda

addons:
  apt:
    packages:
      - mysql-client-5.6
      - mysql-client-core-5.6
      - mysql-server-5.6
  hosts:
    - localhost

script:
  - make ci-test
